# Generated by Django 5.1.4 on 2025-09-14 13:51

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='digital_signature',
            field=models.ImageField(blank=True, help_text='Digital signature for invoices', null=True, upload_to=users.models.user_signature_upload_path),
        ),
        migrations.AddField(
            model_name='user',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo for invoices', null=True, upload_to=users.models.user_logo_upload_path),
        ),
    ]
